import img1 from "../images/home/pic1.jpg";
import img2 from "../images/home/pic2.jpg";
import img3 from "../images/home/pic3.jpg";
import img4 from "../images/home/pic4.jpg";
import img5 from "../images/home/pic5.jpg";
import img6 from "../images/home/pic6.jpg";
import img7 from "../images/home/pic7.jpg";
import img8 from "../images/home/pic8.jpg";
import img9 from "../images/home/pic9.jpg";
import img10 from "../images/home/pic10.jpg";
import img11 from "../images/home/pic11.jpg";
import img12 from "../images/home/pic12.jpg";

const home = [
  {
    count: 0,
    total: 0,
    id: "1",
    name: "Iphone 14",
    cost: "₹ 74,999",
    img: img1,
  },
  {
    count: 0,
    total: 0,
    id: "2",
    name: "Oneplus 11",
    cost: "₹ 54,999",
    img: img2,
  },
  {
    count: 0,
    total: 0,
    id: "3",
    name: "S23 Ultra",
    cost: "₹ 64,999",
    img: img3,
  },
  {
    count: 0,
    total: 0,
    id: "4",
    name: "Levi Jeans",
    cost: "₹ 3,499",
    img: img4,
  },
  {
    count: 0,
    total: 0,
    id: "5",
    name: "Macbook Pro",
    cost: "₹ 1,19,999",
    img: img5,
  },
  {
    count: 0,
    total: 0,
    id: "6",
    name: "Wrangler Shirt",
    cost: "₹ 2,500",
    img: img6,
  },
  {
    count: 0,
    total: 0,
    id: "7",
    name: "Wrangler Denim",
    cost: "₹ 4,500",
    img: img7,
  },
  {
    count: 0,
    total: 0,
    id: "8",
    name: "Woodland Boots",
    cost: "₹ 9,999",
    img: img8,
  },
  {
    count: 0,
    total: 0,
    id: "9",
    name: "Sparx Sandal",
    cost: "₹ 3,200",
    img: img9,
  },
  {
    count: 0,
    total: 0,
    id: "10",
    name: "Sony Earbuds",
    cost: "₹ 7,499",
    img: img10,
  },
  {
    count: 0,
    total: 0,
    id: "11",
    name: "Dell Inspiron",
    cost: "₹ 45,200",
    img: img11,
  },
  {
    count: 0,
    total: 0,
    id: "12",
    name: "Oneplus Watch",
    cost: "₹ 14,999",
    img: img12,
  },
];

const electronics = [
  {
    count: 0,
    total: 0,
    id: "13",
    name: "Iphone 14",
    cost: "₹ 74,999",
    img: img1,
  },
  {
    count: 0,
    total: 0,
    id: "14",
    name: "Oneplus 11",
    cost: "₹ 54,999",
    img: img2,
  },
  {
    count: 0,
    total: 0,
    id: "15",
    name: "S23 Ultra",
    cost: "₹ 64,999",
    img: img3,
  },
  {
    count: 0,
    total: 0,
    id: "16",
    name: "Levi Jeans",
    cost: "₹ 3,499",
    img: img4,
  },
  {
    count: 0,
    total: 0,
    id: "17",
    name: "Macbook Pro",
    cost: "₹ 1,19,999",
    img: img5,
  },
  {
    count: 0,
    total: 0,
    id: "18",
    name: "Wrangler Shirt",
    cost: "₹ 2,500",
    img: img6,
  },
  {
    count: 0,
    total: 0,
    id: "19",
    name: "Wrangler Denim",
    cost: "₹ 4,500",
    img: img7,
  },
  {
    count: 0,
    total: 0,
    id: "20",
    name: "Woodland Boots",
    cost: "₹ 9,999",
    img: img8,
  },
  {
    count: 0,
    total: 0,
    id: "21",
    name: "Sparx Sandal",
    cost: "₹ 3,200",
    img: img9,
  },
  {
    count: 0,
    total: 0,
    id: "22",
    name: "Sony Earbuds",
    cost: "₹ 7,499",
    img: img10,
  },
  {
    count: 0,
    total: 0,
    id: "23",
    name: "Dell Inspiron",
    cost: "₹ 45,200",
    img: img11,
  },
  {
    count: 0,
    total: 0,
    id: "24",
    name: "Oneplus Watch",
    cost: "₹ 14,999",
    img: img12,
  },
];

const fashion = [
  {
    count: 0,
    total: 0,
    id: "25",
    name: "Iphone 14",
    cost: "₹ 74,999",
    img: img1,
  },
  {
    count: 0,
    total: 0,
    id: "26",
    name: "Oneplus 11",
    cost: "₹ 54,999",
    img: img2,
  },
  {
    count: 0,
    total: 0,
    id: "27",
    name: "S23 Ultra",
    cost: "₹ 64,999",
    img: img3,
  },
  {
    count: 0,
    total: 0,
    id: "28",
    name: "Levi Jeans",
    cost: "₹ 3,499",
    img: img4,
  },
  {
    count: 0,
    total: 0,
    id: "29",
    name: "Macbook Pro",
    cost: "₹ 1,19,999",
    img: img5,
  },
  {
    count: 0,
    total: 0,
    id: "30",
    name: "Wrangler Shirt",
    cost: "₹ 2,500",
    img: img6,
  },
  {
    count: 0,
    total: 0,
    id: "31",
    name: "Wrangler Denim",
    cost: "₹ 4,500",
    img: img7,
  },
  {
    count: 0,
    total: 0,
    id: "32",
    name: "Woodland Boots",
    cost: "₹ 9,999",
    img: img8,
  },
  {
    count: 0,
    total: 0,
    id: "33",
    name: "Sparx Sandal",
    cost: "₹ 3,200",
    img: img9,
  },
  {
    count: 0,
    total: 0,
    id: "34",
    name: "Sony Earbuds",
    cost: "₹ 7,499",
    img: img10,
  },
  {
    count: 0,
    total: 0,
    id: "35",
    name: "Dell Inspiron",
    cost: "₹ 45,200",
    img: img11,
  },
  {
    count: 0,
    total: 0,
    id: "36",
    name: "Oneplus Watch",
    cost: "₹ 14,999",
    img: img12,
  },
];

export { home, electronics, fashion };
